Run rabbitmq-cli tests again if they fail the first time
We keep hitting the following error in both OTP v21.3 & v22.3:

    == Compilation error in file test/ctl/set_log_level_command_test.exs ==
    ** (exit) exited in: :gen_server.call(#PID<3.3138.0>, {:read_cache, -576460752303380734}, :infinity)
        ** (EXIT) no connection to nonode@nohost
    ##[error]    (stdlib 3.8) gen_server.erl:223: :gen_server.call/3
    ##[error]    (stdlib 3.8) erl_eval.erl:680: :erl_eval.do_apply/6
    ##[error]    (stdlib 3.8) erl_eval.erl:888: :erl_eval.expr_list/6
    ##[error]    (stdlib 3.8) erl_eval.erl:411: :erl_eval.expr/5
    ##[error]    (elixir 1.10.2) lib/kernel/parallel_compiler.ex:396: Kernel.ParallelCompiler.require_file/2
    ##[error]    (elixir 1.10.2) lib/kernel/parallel_compiler.ex:306: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7

In the meantime, I've asked for help on the Elixir forum:
https://elixirforum.com/t/intermittent-compilation-errors-read-cache-infinity-when-running-tests-in-github-actions/30284

Signed-off-by: Gerhard Lazu <gerhard@lazu.co.uk>

diff --git a/.github/workflows/otp-22.3.yml b/.github/workflows/otp-22.3.yml
--- a/.github/workflows/otp-22.3.yml
+++ b/.github/workflows/otp-22.3.yml
@@ -72,7 +72,11 @@ jobs:
         run: |
           branch_or_tag_name=${GITHUB_REF#refs/*/}
           make -C deps/rabbitmq_server_release start-background-broker PLUGINS="rabbitmq_federation rabbitmq_stomp" DEPS_DIR=$PWD/deps
-          make -C deps/rabbitmq_cli tests DEPS_DIR=$PWD/deps base_rmq_ref=master current_rmq_ref=$branch_or_tag_name DEPS_DIR=$PWD/deps
+          if ! make -C deps/rabbitmq_cli tests DEPS_DIR=$PWD/deps base_rmq_ref=master current_rmq_ref=$branch_or_tag_name DEPS_DIR=$PWD/deps V=2
+          then
+            echo "Run rabbitmq-cli tests again, because: https://elixirforum.com/t/intermittent-compilation-errors-read-cache-infinity-when-running-tests-in-github-actions/30284"
+            make -C deps/rabbitmq_cli tests DEPS_DIR=$PWD/deps base_rmq_ref=master current_rmq_ref=$branch_or_tag_name DEPS_DIR=$PWD/deps V=2
+          fi
       - name: ON FAILURE UPLOAD TESTS LOGS ARTIFACT
         # https://github.com/marketplace/actions/upload-artifact
         uses: actions/upload-artifact@v2-preview
